# site settings
url: "http://letsta.lk"
baseurl: ""
# "http://abrelatam.org"
twitter_username: go_letstalk
analytics: 'UA-61272908-1'

# build settings
markdown: kramdown

en:
  title: Let's Talk 
  description: "Create your own Text Center using instant messaging"
es:
  title: Let's Talk 
  description: "Crea tu propio Text Center usando mensajería instantánea"
